-- Supabase schema for VIC applications
-- Run in Supabase SQL Editor

create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  application_code text,
  startup_name text not null,
  pitch text,
  problem text,
  solution text,
  stage text,
  industry text[],
  target_customer text,
  support_needed text[],
  founders jsonb,
  attachments jsonb,
  fee_paid boolean default false,
  fee_txn_id text,
  status text default 'submitted',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create sequence if not exists application_sequence start 1;

create or replace function public.generate_application_code()
returns text language sql as $$
  select 'VIC' || to_char(current_date,'YYYY') || '-' || lpad(nextval('application_sequence')::text,6,'0');
$$;

create or replace function public.set_application_code()
returns trigger as $$
begin
  new.application_code := public.generate_application_code();
  new.updated_at := now();
  return new;
end;
$$ language plpgsql;

create trigger trg_set_app_code
before insert on public.applications
for each row execute function public.set_application_code();

create table if not exists public.attachments (
  id bigint generated by default as identity primary key,
  application_id bigint references public.applications(id) on delete cascade,
  type text,
  storage_path text,
  file_name text,
  size_kb int,
  uploaded_at timestamptz default now()
);

create index if not exists idx_applications_status on public.applications(status);
create index if not exists idx_applications_created on public.applications(created_at desc);
